# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--profile", "black"]
#      - id: flake8
#        name: flake8
#        entry: flake8
#        language: system
#        types: [python]
#        exclude: "tests"
#      - id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [python]
#        args: ["--rcfile=.pylintrc"]
#        exclude: "tests|config|alembic/|data/"
